version: "2"

services:
  zookeeper1:
    container_name: zookeeper1
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - kafka_net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    container_name: kafka1
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data_1:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
    networks:
      - kafka_net
    depends_on:
      - zookeeper1
  kafka2:
    container_name: kafka2
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9093:9092"
    volumes:
      - "kafka_data_2:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
    networks:
      - kafka_net
    depends_on:
      - zookeeper1
  kafka3:
    container_name: kafka3
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9094:9092"
    volumes:
      - "kafka_data_3:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - KAFKA_CFG_NODE_ID=3
    networks:
      - kafka_net
    depends_on:
      - zookeeper1

volumes:
  zookeeper_data:
    driver: local
  kafka_data_1:
    driver: local
  kafka_data_2:
    driver: local
  kafka_data_3:
    driver: local
    
networks:
  kafka_net:
